/// Dummy restaurant data with images for the app
class DummyRestaurantData {
  static List<Map<String, dynamic>> getDummyRestaurants() {
    return [
      {
        'id': 'r1',
        'name': 'Burger Lab',
        'logoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
        'category': 'Burgers',
        'isOpen': true,
        'latitude': '31.5204',
        'longitude': '74.3587',
        'offerText': '20% OFF',
        'isFeatured': true,
        'menuItems': [
          {
            'id': 'm1',
            'name': 'Smash Burger',
            'description': 'Double beef patty with special sauce',
            'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80',
            'price': '550',
            'category': 'Burgers',
            'tags': [],
            'isFeatured': true,
          },
          {
            'id': 'm2',
            'name': 'Cheese Burger',
            'description': 'Classic burger with melted cheese',
            'imageUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&q=80',
            'price': '450',
            'category': 'Burgers',
            'tags': [],
          },
        ],
      },
      {
        'id': 'r2',
        'name': 'Pizza Hut',
        'logoUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
        'category': 'Pizza',
        'isOpen': true,
        'latitude': '31.5200',
        'longitude': '74.3580',
        'offerText': 'Free Delivery',
        'isFeatured': true,
        'menuItems': [
          {
            'id': 'm4',
            'name': 'Pepperoni Pizza',
            'description': 'Classic pepperoni with mozzarella',
            'imageUrl': 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80',
            'price': '1200',
            'category': 'Pizza',
            'tags': [],
            'isFeatured': true,
          },
        ],
      },

      {
        'id': 'r3',
        'name': 'KFC',
        'logoUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80',
        'category': 'Chicken',
        'isOpen': true,
        'latitude': '31.5210',
        'longitude': '74.3590',
        'isFeatured': true,
        'menuItems': [
          {
            'id': 'm7',
            'name': 'Zinger Burger',
            'description': 'Spicy chicken fillet burger',
            'imageUrl': 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&q=80',
            'price': '600',
            'category': 'Chicken',
            'tags': [],
            'isFeatured': true,
          },
        ],
      },
      {
        'id': 'r4',
        'name': 'Student Biryani',
        'logoUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
        'category': 'Biryani',
        'isOpen': true,
        'latitude': '31.5215',
        'longitude': '74.3575',
        'offerText': '15% OFF',
        'isFeatured': false,
        'menuItems': [
          {
            'id': 'm10',
            'name': 'Chicken Biryani',
            'description': 'Aromatic rice with tender chicken',
            'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80',
            'price': '350',
            'category': 'Biryani',
            'tags': [],
            'isFeatured': true,
          },
        ],
      },
      {
        'id': 'r5',
        'name': 'China Town',
        'logoUrl': 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80',
        'category': 'Chinese',
        'isOpen': true,
        'latitude': '31.5190',
        'longitude': '74.3595',
        'isFeatured': false,
        'menuItems': [
          {
            'id': 'm13',
            'name': 'Chicken Fried Rice',
            'description': 'Stir-fried rice with chicken',
            'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=80',
            'price': '400',
            'category': 'Chinese',
            'tags': [],
          },
        ],
      },
      {
        'id': 'r6',
        'name': 'BBQ Tonight',
        'logoUrl': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
        'category': 'BBQ',
        'isOpen': true,
        'latitude': '31.5195',
        'longitude': '74.3605',
        'offerText': '10% OFF',
        'menuItems': [
          {
            'id': 'm19',
            'name': 'Seekh Kabab',
            'description': 'Grilled minced meat kebabs',
            'imageUrl': 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400&q=80',
            'price': '400',
            'category': 'BBQ',
            'tags': [],
          },
        ],
      },
      {
        'id': 'r7',
        'name': 'Dunkin Donuts',
        'logoUrl': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80',
        'category': 'Desserts',
        'isOpen': true,
        'latitude': '31.5225',
        'longitude': '74.3570',
        'menuItems': [
          {
            'id': 'm22',
            'name': 'Glazed Donuts',
            'description': 'Classic glazed donuts',
            'imageUrl': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&q=80',
            'price': '600',
            'category': 'Desserts',
            'tags': ['vegetarian'],
          },
        ],
      },
      {
        'id': 'r8',
        'name': 'Starbucks',
        'logoUrl': 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80',
        'category': 'Drinks',
        'isOpen': true,
        'latitude': '31.5230',
        'longitude': '74.3610',
        'menuItems': [
          {
            'id': 'm25',
            'name': 'Caramel Latte',
            'description': 'Espresso with caramel',
            'imageUrl': 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80',
            'price': '450',
            'category': 'Drinks',
            'tags': ['vegetarian'],
          },
        ],
      },
    ];
  }
}
