org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xms256m -Xmx768m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.daemon.jvmargs=-Xmx512m
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.builtInKotlin=false
android.newDsl=false
